apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: streamstateingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
    cert-manager.io/issuer: "letsencrypt-staging" # "letsencrypt-staging"
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: streamstateingress
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - ${organization}.streamstate.org
    secretName: streamstate-internal-cert # < cert-manager will store the created certificate in this secret
  rules:
    - host: ${organization}.streamstate.org
      http:
        paths:
        - path: /ui(/|$)(.*)
          #pathType: Prefix
          backend:
            #service:
            serviceName: argoworkflow-argo-workflows-server
            servicePort: 2746
            #    number: 2746
        - path: /monitoring(/|$)(.*) 
          #pathType: Prefix
          backend:
            #service:
            serviceName: prometheus-server 
            servicePort: 80
                #number: 80
        - path: /grafana(/|$)(.*)
         # pathType: Prefix
          backend:
            serviceName: grafana
            servicePort: 3000
              #name: grafana
              #port: 
              #  number: 3000
        - path: /api(/|$)(.*) # post to /api/rotate, for example
          #pathType: Prefix
          backend:
            serviceName: mainui
            servicePort: 80
            #service:
              #name: mainui
              #port: 
              #  number: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: streamstatesparkhistory
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-redirect-from: http://$host/history/
    nginx.ingress.kubernetes.io/proxy-redirect-to: /sparkhistory/history/
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Accept-Encoding "";
      sub_filter_last_modified off;
      sub_filter '<head>' '<head> <base href="/sparkhistory/">'; # add base url
      sub_filter 'href="/' 'href="'; # remove absolute URL path so base url applies
      sub_filter 'src="/' 'src="'; # remove absolute URL path so base url applies
      sub_filter '/{{num}}/jobs/' '/jobs/';
      sub_filter "setUIRoot('')" "setUIRoot('/sparkhistory')"; # Set UI root for JS scripts
      sub_filter "document.baseURI.split" "document.documentURI.split"; # Executors page issue fix
      sub_filter_once off;
      sub_filter_types text/html text/css text/javascript application/javascript; # Specify filter types to prevent processing all files

      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
    cert-manager.io/issuer: "letsencrypt-staging" 
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: streamstatesparkhistory
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - ${organization}.streamstate.org
    secretName: streamstate-internal-cert # < 
  rules:
    - host: ${organization}.streamstate.org
      http:
        paths:
        - path: /sparkhistory/?(.*)
          #pathType: Prefix
          backend:
            serviceName: spark-history-server
            servicePort: 18080 
            #service:
            #  name: spark-history-server 
            #  port:
            #    number: 18080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: streamstateingressargo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: streamstateingressargo
spec:
  tls: 
  - hosts:
    - ${organization}.streamstate.org
    secretName: streamstate-internal-cert # < 
  rules:
    - host: ${organization}.streamstate.org
      http:
        paths:
        - path: /build/container
          #pathType: Prefix
          backend:
            serviceName: argowebhook
            servicePort: 12000
            #service:
              #name: argowebhook
              #port: 
              #  number: 12000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: streamstateingressstatic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_cache static-cache;
      proxy_cache_valid 404 10m;
      proxy_cache_use_stale error timeout updating http_404 http_500 http_502 http_503 http_504;
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
      proxy_cache_bypass $http_x_purge;
      add_header X-Cache-Status $upstream_cache_status;
      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: streamstateingressstatic
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - ${organization}.streamstate.org
    secretName: streamstate-internal-cert # < already generated
  rules:
    - host: ${organization}.streamstate.org
      http:
        paths:
        - path: /
          backend:
            serviceName: mainui
            servicePort: 80
          #pathType: Prefix
          #backend:
          #  service:
          #    name: mainui
          #    port: 
          #      number: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  annotations:
    kubernetes.io/ingress.class: nginx 
    acme.cert-manager.io/http01-edit-in-place: "true"
    # no need to annotate with cert-manager.io/issuer: "letsencrypt-prod"
    # since the secret is already generated.  Just re-use the secret
  labels:
    app: oauth2-proxy
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - ${organization}.streamstate.org
    secretName: streamstate-internal-cert # < already generated
  rules:
    - host: ${organization}.streamstate.org
      http:
        paths:
        - path: /oauth2
          backend:
            serviceName: oauth2-reverse-proxy
            servicePort: 4180
          #pathType: Prefix
          #backend:
          #  service:
          #    name: oauth2-reverse-proxy
          #    port:
           #     number: 4180
        